ALTER TABLE public.books
  ADD COLUMN IF NOT EXISTS min_pages INTEGER,
  ADD COLUMN IF NOT EXISTS max_pages INTEGER,
  ADD COLUMN IF NOT EXISTS page_pairing_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS special_pages_config JSONB,
  ADD COLUMN IF NOT EXISTS layout_strategy VARCHAR(50),
  ADD COLUMN IF NOT EXISTS layout_random_mode VARCHAR(50),
  ADD COLUMN IF NOT EXISTS assisted_layouts JSONB;

ALTER TABLE public.pages
  ADD COLUMN IF NOT EXISTS page_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS page_pair_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS is_special_page BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_printable BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS layout_variation VARCHAR(50),
  ADD COLUMN IF NOT EXISTS background_variation VARCHAR(50),
  ADD COLUMN IF NOT EXISTS background_transform JSONB;

